In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/erenalpt/YMH451_Lab/main/YMH451-Lab-1.csv')

In [6]:
df

Gün Hava Durumu Sıcaklık     Nem   Yağış Oyun
0    G1     Güneşli    Sıcak  Yüksek  Seyrek  Yok
1    G2     Güneşli    Sıcak  Yüksek   Aşırı  Yok
2    G3      Kapalı    Sıcak  Yüksek  Seyrek  Var
3    G4    Yağmurlu   Ilıman  Yüksek  Seyrek  Var
4    G5    Yağmurlu    Soğuk  Normal  Seyrek  Var
5    G6    Yağmurlu    Soğuk  Normal   Aşırı  Yok
6    G7      Kapalı    Soğuk  Normal   Aşırı  Var
7    G8     Güneşli   Ilıman  Yüksek  Seyrek  Var
8    G9     Güneşli    Soğuk  Normal  Seyrek  Yok
9   G10    Yağmurlu   Ilıman  Normal  Seyrek  Var
10  G11     Güneşli   Ilıman  Normal   Aşırı  Var
11  G12      Kapalı   Ilıman  Yüksek   Aşırı  Yok
12  G13      Kapalı    Sıcak  Normal  Seyrek  Var
13  G14    Yağmurlu   Ilıman  Yüksek   Aşırı  Yok

Pandas kütüphanesi aracılığıyla tablodan “Sıcaklık” ve “Nem” değerlerini siliniz

In [7]:
newdf = df.drop(['Sıcaklık','Nem'], axis=1)
newdf

Gün Hava Durumu   Yağış Oyun
0    G1     Güneşli  Seyrek  Yok
1    G2     Güneşli   Aşırı  Yok
2    G3      Kapalı  Seyrek  Var
3    G4    Yağmurlu  Seyrek  Var
4    G5    Yağmurlu  Seyrek  Var
5    G6    Yağmurlu   Aşırı  Yok
6    G7      Kapalı   Aşırı  Var
7    G8     Güneşli  Seyrek  Var
8    G9     Güneşli  Seyrek  Yok
9   G10    Yağmurlu  Seyrek  Var
10  G11     Güneşli   Aşırı  Var
11  G12      Kapalı   Aşırı  Yok
12  G13      Kapalı  Seyrek  Var
13  G14    Yağmurlu   Aşırı  Yok

Pandas kütüphanesinin metodu olan DataFrame()  ile yukarıda verilen tabloyu oluşturunuz ve tablo hakkında betimleyici istatiksel bilgiler veriniz 

In [8]:
datas = {'Gün': ['G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11','G12', 'G13', 'G14'], 
        'Hava Durumu': ['Güneşli', 'Güneşli', 'Kapalı', 'Yağmurlu', 'Yağmurlu', 'Yağmurlu','Kapalı', 'Güneşli', 'Güneşli', 'Yağmurlu', 'Güneşli', 'Kapalı','Kapalı', 'Yağmurlu'],
        'Sıcaklık': ['Sıcak', 'Sıcak', 'Sıcak', 'Ilıman', 'Soğuk', 'Soğuk', 'Soğuk','Ilıman', 'Soğuk', 'Ilıman', 'Ilıman', 'Ilıman', 'Sıcak', 'Ilıman'],
        'Nem': ['Yüksek', 'Yüksek', 'Yüksek', 'Yüksek', 'Normal', 'Normal','Normal', 'Yüksek', 'Normal', 'Normal', 'Normal', 'Yüksek','Normal', 'Yüksek'],
        'Yağış': ['Seyrek', 'Aşırı', 'Seyrek', 'Seyrek', 'Seyrek', 'Aşırı', 'Aşırı','Seyrek', 'Seyrek', 'Seyrek', 'Aşırı', 'Aşırı', 'Seyrek', 'Aşırı'],
        'Oyun': ['Yok', 'Yok', 'Var', 'Var', 'Var', 'Yok', 'Var', 'Var', 'Yok','Var', 'Var', 'Yok', 'Var', 'Yok']}

In [9]:
df_new = pd.DataFrame(data=datas)
df_new

Gün Hava Durumu Sıcaklık     Nem   Yağış Oyun
0    G1     Güneşli    Sıcak  Yüksek  Seyrek  Yok
1    G2     Güneşli    Sıcak  Yüksek   Aşırı  Yok
2    G3      Kapalı    Sıcak  Yüksek  Seyrek  Var
3    G4    Yağmurlu   Ilıman  Yüksek  Seyrek  Var
4    G5    Yağmurlu    Soğuk  Normal  Seyrek  Var
5    G6    Yağmurlu    Soğuk  Normal   Aşırı  Yok
6    G7      Kapalı    Soğuk  Normal   Aşırı  Var
7    G8     Güneşli   Ilıman  Yüksek  Seyrek  Var
8    G9     Güneşli    Soğuk  Normal  Seyrek  Yok
9   G10    Yağmurlu   Ilıman  Normal  Seyrek  Var
10  G11     Güneşli   Ilıman  Normal   Aşırı  Var
11  G12      Kapalı   Ilıman  Yüksek   Aşırı  Yok
12  G13      Kapalı    Sıcak  Normal  Seyrek  Var
13  G14    Yağmurlu   Ilıman  Yüksek   Aşırı  Yok

(3,4) boyutunda bir dizi oluşturunuz. Oluşturduğunuz bu dizinin boyutunu (6,2) olacak şekilde değiştiriniz

In [10]:
arr = np.random.rand(3,4)
print(arr)
new_arr = arr.reshape(6,2)
print(new_arr)

[[0.08296976 0.06499518 0.11324098 0.75337354]
 [0.06199963 0.33427936 0.32319541 0.30112356]
 [0.02233965 0.6950595  0.04547056 0.21864434]]
[[0.08296976 0.06499518]
 [0.11324098 0.75337354]
 [0.06199963 0.33427936]
 [0.32319541 0.30112356]
 [0.02233965 0.6950595 ]
 [0.04547056 0.21864434]]


İki tane (3,3) boyutunda rastgele sayılardan meydana bir dizi oluşturunuz. Oluşturulan bu diziyi hem yatay hem de dikey olacak şekilde istif (stack) ediniz 

In [11]:
arr_1 = np.random.randint(15, size=(3,3))  
arr_2 = np.random.randint(25, size=(3,3))  
print("Array-1",arr_1, sep='\n')
print("Array-2",arr_2,sep='\n')
## Horitzontal Stack
h_stack = np.hstack((arr_1,arr_2))

## Vertical Stack
v_stack = np.vstack((arr_1,arr_2))

print("Horizontal",h_stack, sep='\n')
print("Vertical",v_stack, sep='\n')


Array-1
[[12  3  4]
 [14 10  6]
 [ 3  4  5]]
Array-2
[[15 21 20]
 [10 15  0]
 [11  1 23]]
Horizontal
[[12  3  4 15 21 20]
 [14 10  6 10 15  0]
 [ 3  4  5 11  1 23]]
Vertical
[[12  3  4]
 [14 10  6]
 [ 3  4  5]
 [15 21 20]
 [10 15  0]
 [11  1 23]]
